export const examples = [
  { name: 'events', title: 'Events', tag: 'Time' },
  { name: 'timezones', title: 'Time Zones', tag: 'Time' },
  { name: 'basic-chart', title: 'Basic Chart', tag: 'Drawing', preset: 'basic-chart' },
  { name: 'curve', title: 'Curve', tag: 'Drawing', preset: 'curve' },
  { name: 'log-scale', title: 'Log Scale', tag: 'Data', preset: 'log-scale' },
  { name: 'ribbon-points', title: 'Marks & Links', tag: 'Drawing', preset: 'ribbon-points' },
  { name: 'annotations', title: 'Annotations', tag: 'Drawing', preset: 'annotations' },
  { name: 'intervals', title: 'Intervals', tag: 'Drawing', preset: 'intervals' },
  { name: 'multiple-series', title: 'Multiple Series', tag: 'Data', preset: 'multiple-series' },
  { name: 'multiple-tracks', title: 'Multiple Tracks', tag: 'Data', preset: 'multiple-tracks' },
  { name: 'decimation', title: 'Decimation', tag: 'Data' },
  { name: 'dynamic-loader', title: 'Dynamic Loader', tag: 'Data' },
  { name: 'live-stream', title: 'Live Stream', tag: 'Data' },
  { name: 'styling', title: 'Styling', tag: 'Drawing' },
  { name: 'financial-chart', title: 'Financial Chart', tag: 'Applications' },
  { name: 'audio-waveform', title: 'Audio Waveform', tag: 'Applications' },
];
