packages:
  - packages/*

update:
  githubActions: true

allowBuilds:
  esbuild: true
  svelte-preprocess: true

minimumReleaseAgeExclude:
  - '@kikuchan/binary-reader@0.1.0-alpha.8'
  - '@kikuchan/calendar@0.1.0-alpha.0'
  - '@kikuchan/decimal@0.1.0-alpha.10'
  - '@types/node@26.3.0'
  - '@typescript-eslint/eslint-plugin@8.68.0'
  - '@typescript-eslint/parser@8.68.0'
  - '@typescript-eslint/project-service@8.68.0'
  - '@typescript-eslint/scope-manager@8.68.0'
  - '@typescript-eslint/tsconfig-utils@8.68.0'
  - '@typescript-eslint/type-utils@8.68.0'
  - '@typescript-eslint/types@8.68.0'
  - '@typescript-eslint/typescript-estree@8.68.0'
  - '@typescript-eslint/utils@8.68.0'
  - '@typescript-eslint/visitor-keys@8.68.0'
  - eslint@10.9.1
  - typescript-eslint@8.68.0
  - '@vitejs/plugin-react@6.1.1'
  - '@types/react-dom@19.2.7'
  - '@vitest/browser-playwright@5.0.0'
  - '@vitest/browser@5.0.0'
  - '@vitest/mocker@5.0.0'
  - '@vitest/pretty-format@5.0.0'
  - '@vitest/spy@5.0.0'
  - '@vitest/ui@5.0.0'
  - '@vitest/utils@5.0.0'
  - bumpp@12.3.0
  - vitest@5.0.0
  - '@eslint/compat@2.1.1'
  - rolldown-plugin-dts@0.28.5
  - tinyexec@1.3.1
  - tsdown@0.23.0
