export const examples = [
  { name: 'events', title: 'Events', tag: 'Time', guide: '/guide/getting-started#accessing-the-selected-time' },
  { name: 'timezones', title: 'Time Zones', tag: 'Time', guide: '/guide/advanced/styling#time-axis-labels' },
  {
    name: 'basic-chart',
    title: 'Basic Chart',
    tag: 'Drawing',
    preset: 'basic-chart',
    guide: '/guide/drawing-a-chart#basic-chart',
  },
  { name: 'curve', title: 'Curve', tag: 'Drawing', preset: 'curve', guide: '/guide/drawing-a-chart#chart-presets' },
  {
    name: 'log-scale',
    title: 'Log Scale',
    tag: 'Data',
    preset: 'log-scale',
    guide: '/guide/drawing-a-chart#log-scale',
  },
  {
    name: 'ribbon-points',
    title: 'Marks & Links',
    tag: 'Drawing',
    preset: 'ribbon-points',
    guide: '/guide/advanced/styling#marks-and-links',
  },
  {
    name: 'annotations',
    title: 'Annotations',
    tag: 'Drawing',
    preset: 'annotations',
    guide: '/guide/advanced/styling#data-driven-styles',
  },
  {
    name: 'intervals',
    title: 'Intervals',
    tag: 'Drawing',
    preset: 'intervals',
    guide: '/guide/advanced/styling#marks-and-links',
  },
  {
    name: 'multiple-series',
    title: 'Multiple Series',
    tag: 'Data',
    preset: 'multiple-series',
    guide: '/guide/drawing-a-chart#multiple-series',
  },
  {
    name: 'multiple-tracks',
    title: 'Multiple Tracks',
    tag: 'Data',
    preset: 'multiple-tracks',
    guide: '/guide/drawing-a-chart#multiple-tracks',
  },
  { name: 'decimation', title: 'Decimation', tag: 'Data', guide: '/guide/drawing-a-chart#decimation' },
  { name: 'dynamic-loader', title: 'Dynamic Loader', tag: 'Data', guide: '/guide/advanced/chunk-loading' },
  { name: 'live-stream', title: 'Live Stream', tag: 'Data', guide: '/guide/advanced/live-streaming' },
  { name: 'styling', title: 'Styling', tag: 'Drawing', guide: '/guide/advanced/styling' },
  { name: 'financial-chart', title: 'Financial Chart', tag: 'Applications' },
  { name: 'audio-waveform', title: 'Audio Waveform', tag: 'Applications' },
];
